- hosts: all
  sudo: yes
  remote_user: vagrant
  tasks:
  - name: Actualizar
    command: sudo apt-get update
  - name: Instalar paquetes python parte 1
    apt: name=python-setuptools state=present
    apt: name=python-dev state=present
    apt: name=libpq-dev state=present
  - name: Instalar paquetes python parte 2
    apt: name=build-essential state=present
    apt: name=python-psycopg2 state=present
  - name: Instalar git
    apt: name=git state=present
  - name: Instalar pip
    apt: name=python-pip state=present
  - name: Instalamos la API del bot
    command: sudo pip install python-telegram-bot
